/** Names of the photos in the image registry (src/assets/index.ts). Kept import-free so /api can use it. */
export type ImageKey =
  | 'aerialRebar'
  | 'apartments'
  | 'concreteBldg'
  | 'concreteFrame'
  | 'craneFrame'
  | 'cranesDusk'
  | 'drafting'
  | 'drawingsDesk'
  | 'electrician'
  | 'fireCeiling'
  | 'glassTowers'
  | 'hardhat'
  | 'heroTower'
  | 'highriseDusk'
  | 'hvacUnit'
  | 'modernBuilding'
  | 'officeServices'
  | 'panelTesting'
  | 'plantRoom'
  | 'rebarColumns'
  | 'siteColumns'
  | 'siteEngineers'
  | 'studio'
  | 'team'
  | 'villa'
